export {
  createEvent,
  getEventById,
  getAllEvents,
  updateEvent,
  deleteEvent,
  createArea,
  getAllAreas,
  getAreaById,
  getAreaByName,
  createPhoto,
  getPhotosByEventId,
  deletePhoto,
  uploadPhoto,
  deleteUploadedPhoto,
  createSchedule,
  getAllSchedules,
  getScheduleById,
  markScheduleCompleted,
  deleteSchedule,
} from './store-provider';
